#!/bin/bash

#sitename
if [ -z "$1" ]; then # if no param
    read -p "Enter name of site: " sitename
else
    sitename=$1
fi

mkdir /var/www/$sitename.local/
chown -R www-data:www-data /var/www/$sitename.local/

#apache 
touch /etc/apache2/sites-available/$sitename.conf
echo "<VirtualHost 127.0.0.1:8080>
            ServerName $sitename.local
            DocumentRoot /var/www/$sitename.local/
    </VirtualHost>" > /etc/apache2/sites-available/$sitename.conf

#nginx
touch /etc/nginx/sites-available/$sitename.conf
echo "server {
        listen   80;
       root /var/www/$sitename.local;
        server_name $sitename.local;

        location / {
          proxy_pass          http://127.0.0.1:8080/;
            proxy_redirect      off;

           proxy_set_header   Host             \$host;
            proxy_set_header   X-Real-IP        \$remote_addr;

           client_max_body_size       64m;
            client_body_buffer_size    128k;

           client_body_temp_path      /var/nginx/client_body_temp;

            proxy_connect_timeout      70;
            proxy_send_timeout         90;
            proxy_read_timeout         90;
            #proxy_send_lowat           12000;
            proxy_buffer_size          4k;
            proxy_buffers              4 32k;
            proxy_busy_buffers_size    64k;
            proxy_temp_file_write_size 64k;

           proxy_temp_path            /var/nginx/proxy_temp;
        }
}" > /etc/nginx/sites-available/$sitename.conf

# finishing
sudo ln -s /etc/nginx/sites-available/$sitename.conf /etc/nginx/sites-enabled/$sitename.conf
a2ensite $sitename
service apache2 restart
service nginx restart